require_relative './bishop.rb'
require_relative './board.rb'
require_relative './board_renderer_text.rb'
require_relative './king.rb'
require_relative './knight.rb'
require_relative './pawn.rb'
require_relative './queen.rb'
require_relative './rook.rb'
